# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '^1.16.0'

      - name: Setup go-task/task
        uses:  Arduino/actions/setup-taskfile@master
        
      - name: Install build tools
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          task install-tools
      
      - name: Clean and Build
        run: |
          export PATH=$PATH:$(go env GOPATH)/bin
          task clean && task
      
      - name: release-please-action
        uses: google-github-actions/release-please-action@v2.19.2
        with:
          release-type: golang
          path: dist
          command: github-release
          default-branch: main
